CC = gcc
CFLAGS = -Wall -Wextra -Werror
SRCS = fdf.c
OBJ = $(SRCS:.c=.o)
NAME = fdf

all :
	$(NAME)

%.o: %.c
	$(CC) -I/usr/include -Imlx_linux -O3 -c $< -o $@

$(NAME): $(OBJ)
	$(CC) $(OBJ) -Lmlx_linux -lmlx_Linux -L/usr/lib -Imlx_linux -lXext -lX11 -lm -lz -o $(NAME)

fclean:
	rm -f $(OBJ) $(NAME)


